ROLE_LABELS = {
    "admin": "👑 Admin",
    "support_teacher": "🧑‍🏫 Support Teacher",
    "student": "🎓 O‘quvchi",
}

TEXT = {
    "uz": {
        "choose_language": "Tilni tanlang:",
        "main_menu": "Nima qilamiz?",
        "share_contact": "Davom etish uchun telefon raqamingizni yuboring yoki raqamni yozing.",
        "share_contact_button": "Telefon raqamni yuborish",
        "not_allowed": "Bu telefon raqam ro‘yxatda yo‘q. Iltimos, administratorga murojaat qiling.",
        "onboarded": "Xush kelibsiz.",
        "support_teachers": "Support Teacherlar",
        "choose_support_type": "Qaysi yo‘nalish bo‘yicha yordam kerak?",
        "my_lessons": "Mening darslarim",
        "no_support_types": "Hali yo‘nalishlar qo‘shilmagan.",
        "no_support": "Bu yo‘nalishda hozircha Support Teacher yo‘q.",
        "booked": "Dars band qilindi.",
        "main_menu_button": "Asosiy menyu",
        "phone_saved": "Telefon raqam saqlandi.",
        "send_own_contact": "Iltimos, o‘zingizning kontaktingizni yuboring.",
        "choose_date_title": "Sana tanlang",
        "choose_date_body": "Dars kunini tanlang.",
        "free_time_title": "Bo‘sh vaqt",
        "free_time_body": "Quyidan vaqtni tanlang.",
        "duration_title": "Davomiylik",
        "duration_body": "Dars davomiyligi 1 soat.",
        "topic_title": "Dars mavzusi",
        "topic_body": "Support Teacherdan nimani o‘rganmoqchi ekaningizni yozing.",
        "back_to_categories": "Yo‘nalishlarga qaytish",
        "previous": "Oldingi",
        "next": "Keyingi",
        "select": "Tanlash",
        "today": "Bugun",
        "tomorrow": "Ertaga",
        "back_to_supports": "Support Teacherlarga qaytish",
        "no_free_time": "Bo‘sh vaqt yo‘q",
        "choose_other_support": "Boshqa Support Teacher tanlash",
        "choose_other_date": "Boshqa sana tanlash",
        "continue_one_hour": "Davom etish — 1 soat",
        "back_to_slots": "Bo‘sh vaqtlarga qaytish",
        "cancel": "Bekor qilish",
        "temporarily_banned": "Siz vaqtincha band qila olmaysiz.",
        "ban_ends": "Ban tugaydi",
        "topic_too_short": "Dars mavzusini kamida 3 ta belgi bilan yozing.",
        "topic_too_long": "Dars mavzusi 500 ta belgidan oshmasligi kerak.",
        "slot_unavailable": "Bu vaqt band yoki mavjud emas.",
        "hours": "soat",
        "topic": "Mavzu",
        "phone": "Telefon",
        "lesson": "Dars",
        "no_active_lessons": "Aktiv darslaringiz yo‘q.",
        "cancel_lesson": "Darsni bekor qilish",
        "lesson_not_found": "Bu dars topilmadi yoki allaqachon bekor qilingan.",
        "cancel_two_hours": "Darsni kamida 2 soat oldin bekor qilish mumkin.",
        "lesson_cancelled": "Dars bekor qilindi.",
        "back_to_lessons": "Darslarimga qaytish",
        "feedback_already_sent": "Bu dars uchun feedback allaqachon yuborilgan.",
        "feedback_thanks": "Feedback uchun rahmat.",
        "rating_request": "Dars uchun baho bering.",
        "lesson_reassigned": "Darsingiz boshqa Support Teacherga o‘tkazildi",
        "new_lesson": "Yangi dars",
        "replacement_not_found": "Hozircha o‘rniga bo‘sh Support Teacher topilmadi.",
        "reminder_20": "Dars 20 daqiqadan keyin boshlanadi.",
        "reminder_5": "Dars 5 daqiqadan keyin boshlanadi.",
        "student_role": "🎓 O‘quvchi",
    },
    "ru": {
        "choose_language": "Выберите язык:",
        "main_menu": "Что делаем?",
        "share_contact": "Чтобы продолжить, отправьте контакт или напишите номер телефона.",
        "share_contact_button": "Отправить номер телефона",
        "not_allowed": "Этот номер телефона не добавлен в список. Обратитесь к администратору.",
        "onboarded": "Добро пожаловать.",
        "support_teachers": "Support Teacher",
        "choose_support_type": "По какому направлению нужна помощь?",
        "my_lessons": "Мои уроки",
        "no_support_types": "Направления ещё не добавлены.",
        "no_support": "В этом направлении пока нет Support Teacher.",
        "booked": "Урок забронирован.",
        "main_menu_button": "Главное меню",
        "phone_saved": "Номер телефона сохранён.",
        "send_own_contact": "Пожалуйста, отправьте свой контакт.",
        "choose_date_title": "Выберите дату",
        "choose_date_body": "Выберите день урока.",
        "free_time_title": "Свободное время",
        "free_time_body": "Выберите время ниже.",
        "duration_title": "Продолжительность",
        "duration_body": "Продолжительность урока — 1 час.",
        "topic_title": "Тема урока",
        "topic_body": "Напишите, что вы хотите изучить с Support Teacher.",
        "back_to_categories": "Назад к направлениям",
        "previous": "Назад",
        "next": "Далее",
        "select": "Выбрать",
        "today": "Сегодня",
        "tomorrow": "Завтра",
        "back_to_supports": "Назад к Support Teacher",
        "no_free_time": "Нет свободного времени",
        "choose_other_support": "Выбрать другого Support Teacher",
        "choose_other_date": "Выбрать другую дату",
        "continue_one_hour": "Продолжить — 1 час",
        "back_to_slots": "Назад к свободному времени",
        "cancel": "Отмена",
        "temporarily_banned": "Вы временно не можете бронировать уроки.",
        "ban_ends": "Блокировка закончится",
        "topic_too_short": "Тема урока должна содержать не менее 3 символов.",
        "topic_too_long": "Тема урока не должна превышать 500 символов.",
        "slot_unavailable": "Это время занято или недоступно.",
        "hours": "ч.",
        "topic": "Тема",
        "phone": "Телефон",
        "lesson": "Урок",
        "no_active_lessons": "У вас нет активных уроков.",
        "cancel_lesson": "Отменить урок",
        "lesson_not_found": "Урок не найден или уже отменён.",
        "cancel_two_hours": "Урок можно отменить не позднее чем за 2 часа.",
        "lesson_cancelled": "Урок отменён.",
        "back_to_lessons": "Назад к моим урокам",
        "feedback_already_sent": "Отзыв для этого урока уже отправлен.",
        "feedback_thanks": "Спасибо за отзыв.",
        "rating_request": "Оцените урок.",
        "lesson_reassigned": "Ваш урок перенесён к другому Support Teacher",
        "new_lesson": "Новый урок",
        "replacement_not_found": "Свободный Support Teacher на замену пока не найден.",
        "reminder_20": "Урок начнётся через 20 минут.",
        "reminder_5": "Урок начнётся через 5 минут.",
        "student_role": "🎓 Ученик",
    },
}


def normalize_lang(language: str | None) -> str:
    return language if language in TEXT else "uz"


def t(key: str, language: str | None = "uz") -> str:
    return TEXT[normalize_lang(language)].get(key, key)


def role_label(role: str, language: str | None = "uz") -> str:
    if role == "student":
        return t("student_role", language)
    return ROLE_LABELS.get(role, role)


def title(title_text: str, body: str) -> str:
    return f"{title_text}\n{body}"
